MACRO( USE_PRECOMPILED_HEADER PRECOMPILED_HEADER PRECOMPILED_SOURCE )
    add_definitions(/Yu"${PRECOMPILED_HEADER}")
    set_source_files_properties(${PRECOMPILED_SOURCE}
      PROPERTIES COMPILE_FLAGS /Yc"${PRECOMPILED_HEADER}"
    )
ENDMACRO( USE_PRECOMPILED_HEADER )


FUNCTION( SOURCE_GROUP_EXT DIRECTORY EXTENSION PREFIX )

    FILE( GLOB_RECURSE SOURCES ${DIRECTORY}/${EXTENSION} )

    FOREACH( FILE ${SOURCES} )
        GET_FILENAME_COMPONENT( FULLPATH ${FILE} PATH )

        STRING( REPLACE ${DIRECTORY} ${PREFIX} PATH ${FULLPATH} )
        STRING( REPLACE / \\ GROUP ${PATH} )
        SOURCE_GROUP( ${GROUP} FILES ${FILE} )
    ENDFOREACH( FILE ${SOURCES} )   

ENDFUNCTION( SOURCE_GROUP_EXT )


MACRO( SET_WARNING_LEVEL LEVEL )

    IF(CMAKE_BUILD_TOOL MATCHES "(msdev|devenv|nmake)")

        IF(CMAKE_CXX_FLAGS MATCHES "/W[0-4]")
            STRING(REGEX REPLACE "/W[0-4]" "/W${LEVEL}" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
        ELSE()
            SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W${LEVEL}")
        ENDIF()

        IF(CMAKE_C_FLAGS MATCHES "/W[0-4]")
            STRING(REGEX REPLACE "/W[0-4]" "/W${LEVEL}" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
        ELSE()
            SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /W${LEVEL}")
        ENDIF()

    ENDIF(CMAKE_BUILD_TOOL MATCHES "(msdev|devenv|nmake)")

ENDMACRO( SET_WARNING_LEVEL )
